### ISSUE TITLE
Is it safe to install this with Python 3.12? Can I install ftCLI on top of the FontTools distribution?

### ISSUE THREAD

**Issue by fmotion1** [ftCLI/FoundryTools-CLI#118]
The README states it's discouraged to install with Python 3.11. What about 3.12? I _was_ able to successfully install [AFDKO](https://github.com/adobe-type-tools/afdko) on 3.12 in a separate VENV. It also looks like AFDKO 4.0.0 gets installed by default when installing FontTools. But I have a couple further questions:

1. Can I just install `ftCLI` on top of the latest [FontTools](https://github.com/fonttools) distribution? 
2. [AFDKO](https://github.com/adobe-type-tools/afdko) is currently at 4.0.0 and seems like it gets installed by default when installing [FontTools](https://github.com/fonttools/fonttools). Will this version play nice with ftCLI?
3. What is the optimal way to install FontTools, ftCLI, and AFDKO in one VENV? Is it possible?

I want to minimize the amount of VENVs that I'm creating and hoping that version conflicts won't be an issue.

Thanks for any assistance.

**Comment by alerque** [comment]
It would be helpful if you explicitly stated what the expected issue with Python 3.11/3.12 is. I package this for Arch Linux for which the only real option is the system Python version (currently 3.12) and don't know of any issues. If it should (have been?) held back that should have been documented in the setup file so it wouldn't build. If it doesn't matter then why the vagueness about "it depends"?

As of now `ftcli` packages for Arch are running on 3.11.5 with no known issues, but I only test a limited subset of functions myself.

**Comment by ftCLI** [comment]
From AFDKO's [README](https://github.com/adobe-type-tools/afdko#installation):

> The AFDKO requires [Python](http://www.python.org/download) 3.8 or later. It should work with any Python > 3.8, but occasionally tool-chain components and dependencies don't keep pace with major Python releases, so there might be some lag time while they catch up.

From FoundryTools-CLI [README](https://github.com/ftCLI/FoundryTools-CLI#installation)

> **Note for Windows users**: installation on Python 3.11 is strongly discouraged because AFDKO doesn't support it, and an attempt of installation would probably fail. Since macOS users successfully installed FoundryTools-CLI on Python 3.11, requirements have been loosened up.

Actually, on a clean Windows 10 virtual machine with only Python 3.12 installed, the installation fails while attempting to install psautohint.

To clarify "depends": if @fmotion1 was able to install AFDKO, probably he has the correct "Microsoft C++ Build Tools" installed. As far as I know, there's no more a standalone installer for  Microsoft C++ Build Tools to link in the README.

psautohint is no more a required dependency for foundrytools-cli, but for some reason it's still required by AFDKO (that now uses otfautohint).

In the README file I state that installation is strongly discouraged in Python 3.11 in Windows. Maybe I should update with Python 3.12 too.

```bash
Building wheels for collected packages: psautohint
  Building wheel for psautohint (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for psautohint (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      C:\Users\cg\AppData\Local\Temp\pip-build-env-0a1l9sj0\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\psautohint
      copying python\psautohint\autohint.py -> build\lib.win-amd64-cpython-312\psautohint
      copying python\psautohint\fdTools.py -> build\lib.win-amd64-cpython-312\psautohint
      copying python\psautohint\otfFont.py -> build\lib.win-amd64-cpython-312\psautohint
      copying python\psautohint\ufoFont.py -> build\lib.win-amd64-cpython-312\psautohint
      copying python\psautohint\__init__.py -> build\lib.win-amd64-cpython-312\psautohint
      copying python\psautohint\__main__.py -> build\lib.win-amd64-cpython-312\psautohint
      running build_clib
      building 'psautohint' library
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psautohint
Failed to build psautohint
ERROR: Could not build wheels for psautohint, which is required to install pyproject.toml-based projects
```

**Comment by ftCLI** [comment]
Update: I made some more tests on Windows 10 x64. If Visual Studio 2022 is installed, `ADFKO` and `psautohint` installations succeed. To install the necessary tools, check **Python development** and, in the right panel, the optional **Python native development tools** 

![Annotation 2023-10-28 154642](https://github.com/ftCLI/FoundryTools-CLI/assets/83063506/3b35dcdd-011b-4bf3-bb92-808a5c761850)

I think that writing a wiki and updating the README file with a link to it is the best option, but suggestions are welcome.

**Comment by ftCLI** [comment]
Issue closed. To answer @fmotion1:

> 1. Can I just install `ftCLI` on top of the latest [FontTools](https://github.com/fonttools) distribution?
Yes, latest FontTools version is supported

> 2. [AFDKO](https://github.com/adobe-type-tools/afdko) is currently at 4.0.0 and seems like it gets installed by default when installing [FontTools](https://github.com/fonttools/fonttools). Will this version play nice with ftCLI?
Yes, this version works and 4.0.0 is the min version required.

> 3. What is the optimal way to install FontTools, ftCLI, and AFDKO in one VENV? Is it possible?
`python -m pip install foundrytools-cli`
