### ISSUE TITLE
Weird render effect in IDEA

### ISSUE THREAD

**Issue by subframe7536** [ftCLI/FoundryTools-CLI#166]
Thanks for your great work!

I'm making a new monospace variable font and instantiate it using: `ftcli converter vf2i {input_file} -out {output_ttf}`

Everything works well until I encounter a issue https://github.com/subframe7536/maple-font/issues/182. The character spacing will change between different font weights in small font size, and the issue resolved when the font is exported by FontLab.

I need some help to deal with this issue, thanks🙏

**Comment by ftCLI** [comment]
Can the fonts with the issue be posted here?

**Comment by subframe7536** [comment]
sure, just the [release file](https://github.com/subframe7536/maple-font/releases/download/v7.0-beta15/MapleMono-TTF.zip)

**Comment by subframe7536** [comment]
ttf

Also, thanks for point that out. I have poor knowledge in font tables

**Comment by ftCLI** [comment]
I have PyCharm and have the same issue for the Thin and ExtraLight cuts,

The issue seems to disappear it I change the usWeightClass as follows:

```
Thin: 100 -> 250
ExtraLight: 200 -> 275
```

See image
![pasted](https://github.com/ftCLI/FoundryTools-CLI/assets/83063506/8c526d19-6062-40b1-ae93-0515dd8c586d)

Let me know if it works for you.

More: I have fixed the name table, so keep these files: 
[MapleMono-TTF (fix).zip](https://github.com/ftCLI/FoundryTools-CLI/files/15217793/MapleMono-TTF.fix.zip)

**Comment by subframe7536** [comment]
> More: I have fixed the name table, so keep these files: [MapleMono-TTF (fix).zip](https://github.com/ftCLI/FoundryTools-CLI/files/15217793/MapleMono-TTF.fix.zip)

I test with `Light` and `Regular`, it works well, but the `usWeightClass` in `Light` is not changed. How to make it possible?

**Comment by ftCLI** [comment]
To show the name table viewer: ftcli `print font-names PATH`

This is how I patched the fonts:

In the MapleMono-TTF folder, run `ftcli assistant ui .`

![image](https://github.com/ftCLI/FoundryTools-CLI/assets/83063506/5b87e983-0948-4969-b798-d64f264bcfe4)

Recalculate the values by pressing c and using the default choice (0)

![pasted](https://github.com/ftCLI/FoundryTools-CLI/assets/83063506/704c500e-031f-4993-8aa1-2d21b87e039f)

Look how the weight class changed:

![Cattura](https://github.com/ftCLI/FoundryTools-CLI/assets/83063506/0678d19e-adec-4f9a-9aca-167062614374)

Now, press x to exit and run the following:

`ftcli assistant commit . -ls 400 700`

![pasted](https://github.com/ftCLI/FoundryTools-CLI/assets/83063506/7bbd966e-3990-42c6-b859-164f4bb786c8)

Final touch, to delete all names from the Macintosh table except 1, 2, 4, 5 and 6:

`ftcli name del-mac-names .`

**Comment by ftCLI** [comment]
Read more about the usWeightClass < 250 issue here: https://forum.glyphsapp.com/t/weight-classes-differences-in-glyphs-2-5/8701

**Comment by ftCLI** [comment]
> I test with `Light` and `Regular`, it works well, but the `usWeightClass` in `Light` is not changed. How to make it possible?

Because Light has usWeightClass value = 300, that is greater than 250

**Comment by subframe7536** [comment]
Thanks for such detailed guide!

> Because Light has usWeightClass value = 300, that is greater than 250

But as for `Jetbrains Mono`, it renders correctly, even if it has 100 for `Thin` and 200 for `ExtraLight` (which I reference from)

I finally fix it in my local machine by load and save the variable font 😅
https://github.com/subframe7536/maple-font/commit/f5e5307da7059e8a45bc03bd0a8459aaa5e5775a

**Comment by ftCLI** [comment]
> But as for `Jetbrains Mono`, it renders correctly, even if it has 100 for `Thin` and 200 for `ExtraLight` (which I reference from)

Yes, Light should work well regardless of the weight classes of other cuts. The issue if for styeles with usWeightClass lower than 250, so 300 is not affected.

Do you still face the issue? I closed PyCharm, uninstalled the first version, installed the patched files (all the family) and the re-opened PyCharm.

**Comment by subframe7536** [comment]
Noop, it is solved by following your guide. Just try to find out the reason.

Moreover, is there any way to process it programmly? the `ftcli assistant ui .` seems to have no option to run without interaction

**Comment by ftCLI** [comment]
If the fonts you export from variable have the correct usWeightClass values, you could just run:

```
ftcli assistant init .
ftcli assistant commit . -ls 400 700
```

If Thin and ExtraLight are still 100 and 200, it's a bit more complex. The tool is not thought to be command-line only because every designer uses his custom style names (Hairline, UltraLight, ExtraThin) or uses the default names for different weight classes (sometimes Book is 350, other times 450). So fine tuning requires manual intervention.

A command to recalculate values without interaction could be added, but you must be sure that the styles mapping (see ftCLI_files/styles_mapping.json file) is correct. I'll think about it and in case I'll make a release.

**Comment by subframe7536** [comment]
I have setup `Extralight` and `Thin` and try to fix it in https://github.com/subframe7536/maple-font/commit/c5a04b8d2ff64b5fdcea77597ee977066b240cfe, but still have no effect unless manually run the `ftcli assistant ui .`. I think it may be solve by the recalculation

**Comment by ftCLI** [comment]
Fonts have italic bits not properly set, be careful. And still the names are messed.

Try the following (order is important):

```
ftcli fix italic-angle .
ftcli assistant init .
ftcli assistant commit . -ls 400 700
```

**Comment by subframe7536** [comment]
hmmm... it correctly rendered when fix the name, but the option fails 

![image](https://github.com/ftCLI/FoundryTools-CLI/assets/78338239/0c0b4d20-8da3-4841-88f8-2c852c96e2cd)

**Comment by ftCLI** [comment]
That's correct. The fonts are grouped under the same family and you can choose the regular and bold styles under the Typography Settings panel.

Try to install on Windows the files int the 250&275.zip archive you posted before. On Windows 10, I only get 9 styles installed. The other 7 become accessible once I uninstall the others.

A basice principle: NameID 2 can have only the following values: Regular, Italic, Bold, Bold Italic.

Not correct:

```
NameID1: Maple Mono
NamiID2: ExtraBold
```

Correct:

```
NameID1: Maple Mono ExtraBold
NameID2: Regular
NameID16: Maple Mono
NameID17: ExtraBold
```

This is what the ftcli assistand does: apply the weight/width class values from the CSV file, set the Bold/Italic/Oblique bits and correctly compile the name table.

**Comment by ftCLI** [comment]
Anyway, what's your process? You convert the variable fonts to static? And then?

**Comment by subframe7536** [comment]
Everything works now😊 I am deeply thankful for your thorough investigation and help in addressing this problem😘

![recording](https://github.com/ftCLI/FoundryTools-CLI/assets/78338239/37cc16eb-e4cb-473b-bb0c-7bb617934ac1)

**Comment by subframe7536** [comment]
Seems that `Regular` / `Italic` / `Bold` / `Bold Italic` should remove NameID 16 & 17
https://github.com/subframe7536/maple-font/issues/183

**Comment by ftCLI** [comment]
Yes, they are not added (or automatically deleted if present) when you use the `-ls/--linked-styles` option. They were still present?

**Comment by subframe7536** [comment]
Oh... Find that I call them before manually setup the name

Everything works well

**Comment by ftCLI** [comment]
I'd check the uni0259 contour in MapleMono-ExtraLightItalic, seems broken.

More: after the variable to static conversion, I'd add a line to check the contours of the TTFs

```python
run(f"ftcli fix italic-angle {output_ttf}")
run(f"ftcli ttf fix-contours {output_ttf}")
run(f"ftcli assistant init {output_ttf}")
run(f"ftcli assistant commit {output_ttf} -ls 400 700")
shutil.rmtree(path.join(output_ttf, "ftCLI_files"))
```

This ensures that the contours direction is correct and that overlaps and tiny paths are removed.

A tiny path is present in the 'thorn' glyph of MapleMono-Bold

Before:

![pasted](https://github.com/ftCLI/FoundryTools-CLI/assets/83063506/8a3c799d-6ea2-41e9-af13-51f0024bdc14)

After:

![image](https://github.com/ftCLI/FoundryTools-CLI/assets/83063506/880a8d65-980a-4701-ba6f-99cb3ab1d3b6)

**Comment by subframe7536** [comment]
Thanks for so much wonderful tools!
