### ISSUE TITLE
Setting hhea linegap with value 0 not valid

### ISSUE THREAD

**Issue by ddaanniiieeelll** [ftCLI/FoundryTools-CLI#179]
Using 
`ftcli hhea --linegap 0 <input-path>`

results in:

```
[ ERROR    ] Please, pass at least a valid parameter.
[ INFO     ] Elapsed time: 0.0001 seconds
```

Seems like it’s not possible to set hhea linegap to 0, but what to do if the linegap needs to be 0?

v: 1.1.14

**Comment by ftCLI** [comment]
Thanks indeed, I wans't checking if the values were `None`.

Would you check v1.1.16? I fixed the errors in this release

**Comment by ddaanniiieeelll** [comment]
Setting hhea lineGap to 0 works great with v1.1.16!

Thanks for the quick fix!!
