### ISSUE TITLE
Tag for 0.9.8 has capital "V"

### ISSUE THREAD

**Issue by alerque** [ftCLI/FoundryTools-CLI#27]
...should probably be lower case like all the other releases and standard versioning schemes.

Also release automation stuff should ideally be setup to only act on tag patterns that fit the mold to avoid issues like this.

**Comment by ftCLI** [comment]
Sorry, was a typo.

I just deleted the release and made a new one with the correct tag.

> Also release automation stuff should ideally be setup to only act on tag patterns that fit the mold to avoid issues like this.

Any hint on how to setupt this?

**Comment by alerque** [comment]
It looks like maybe you aren't posting releases from a workflow at all, only post-release upload to PyPi. In that case you are just subject to your own typos. I idea was that releases were posted automatically using an action using a trigger like `on: [ tag = "v*.*.*" ]`.

**Comment by ftCLI** [comment]
Ok, thanks!

I'll try to setup the workflow. I leave the issue open.
